/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;
import Server.ServerInterface;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author new laptop
 */
public class ClientForm extends javax.swing.JFrame {

    ServerInterface serverInterface;
    String name,id,name_of_clientInterface;
    ClientInterface clientInterface;
    boolean isConnected=false;
    /**
     * Creates new form CilentForm
     */
    public ClientForm() {

        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListOfUsers = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        connect_to_server = new javax.swing.JButton();
        tfmsg = new javax.swing.JTextField();
        sendMessage = new javax.swing.JButton();
        tfdirectory = new javax.swing.JTextField();
        tffile = new javax.swing.JTextField();
        SearchFile = new javax.swing.JButton();
        tfidClient = new javax.swing.JTextField();
        tfnameclient = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_messages = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close_event(evt);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Client :");

        ListOfUsers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(ListOfUsers);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Online Users :");

        connect_to_server.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        connect_to_server.setText("Connect To Server");
        connect_to_server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_to_serverActionPerformed(evt);
            }
        });

        tfmsg.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        sendMessage.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sendMessage.setText("Send Message");
        sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageActionPerformed(evt);
            }
        });

        tfdirectory.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        tffile.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        SearchFile.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        SearchFile.setText("Search File");
        SearchFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFileActionPerformed(evt);
            }
        });

        tfidClient.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        tfnameclient.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tfnameclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameclientActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Directory :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("File :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("ID Client :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Name Client :");

        ta_messages.setColumns(20);
        ta_messages.setRows(5);
        jScrollPane1.setViewportView(ta_messages);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(225, 225, 225)
                                        .addComponent(connect_to_server))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tffile, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sendMessage)
                                            .addComponent(SearchFile, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tfidClient, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfnameclient, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))))
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchFile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tffile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnameclient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfidClient)
                            .addComponent(connect_to_server))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connect_to_serverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_to_serverActionPerformed
        String nameClient=tfnameclient.getText(),idClient=tfidClient.getText();
        if( nameClient.length()!=0 && idClient.length()!=0 && !isConnected){
        Registry registry;
            try { 
                name=nameClient ;
                  id=idClient;
                name_of_clientInterface="clientInterface_"+id;
                clientInterface=new ClientClass(this);
                registry = LocateRegistry.getRegistry("localhost", 5555);
                registry.rebind(name_of_clientInterface, clientInterface);
                  serverInterface =(ServerInterface) registry.lookup("serverInterface");
                  serverInterface.connect_to_server(name, Integer.parseInt(id), name_of_clientInterface);
                  title.setText("Client : "+id+" "+name);
                 isConnected=true;
            } catch (Exception ex) {
              /*
                Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);*/
                    showMessageDialog(this, ex);
            } 

        }
        else if(isConnected)
            showMessageDialog(this, "You'r Connected before ");
        
        tfnameclient.setText("");
        tfidClient.setText("");

    }//GEN-LAST:event_connect_to_serverActionPerformed
     public  void update_Users(List<String> users)
    {
        DefaultListModel listmodelUser=new DefaultListModel();
        for(String user :users)
        {
            listmodelUser.addElement(user);
        }
        ListOfUsers.setModel(listmodelUser);
    }
 
     public  void update_message(String msg)
     {
         ta_messages.append(msg);

     }
    private void SearchFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchFileActionPerformed
     
        if(serverInterface==null){
            showMessageDialog(this,"Connect To Server Please");
        }
        else
        {
            String dir=tfdirectory.getText(),file=tffile.getText(); // get Directory and file 
            if(dir.length()!=0 && file.length()!=0){
                try {
                String  result_search= serverInterface.SearchFile(file,dir);
              
                showMessageDialog(this ,result_search);
                } catch (Exception ex) {
             
            //    Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
                    showMessageDialog(this, ex);
            }
            }
        }
        tfdirectory.setText("");
        tffile.setText("");
     
        
                
    }//GEN-LAST:event_SearchFileActionPerformed

    private void tfnameclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameclientActionPerformed

    private void sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageActionPerformed
      
         if(serverInterface==null){
            showMessageDialog(this,"Connect To Server, Please");
        }
        else
        {
            String msg=tfmsg.getText();
            if(msg.length()!=0 ){
                try {
                    serverInterface.send_msg(name, msg);
              
            } catch (Exception ex) {
                /*
                Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);*/
                    showMessageDialog(this, ex);
            }
            }
        }
         tfmsg.setText("");
    }//GEN-LAST:event_sendMessageActionPerformed

    private void close_event(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_close_event
        try {
            if(serverInterface!=null){
            serverInterface.send_msg(name, " I Will Leave Now , Bye Bye  ");
            serverInterface.leave_chat(Integer.parseInt(id), name);}
        } catch (Exception ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_close_event

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ClientForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListOfUsers;
    private javax.swing.JButton SearchFile;
    private javax.swing.JButton connect_to_server;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sendMessage;
    private javax.swing.JTextArea ta_messages;
    private javax.swing.JTextField tfdirectory;
    private javax.swing.JTextField tffile;
    private javax.swing.JTextField tfidClient;
    private javax.swing.JTextField tfmsg;
    private javax.swing.JTextField tfnameclient;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
